### ISSUE TITLE
We should triage feedback from the alpha community calls.

### ISSUE THREAD

**Issue by chadsansing** [mozilla/olm-whitepaper#13]
See link: https://public.etherpad-mozilla.org/p/olm-whitepaper-call

**Comment by chadsansing** [comment]
Decision log shaping up [here](https://docs.google.com/document/d/1ocnwUCmL6w7SeRiFQTdyJSJYlrrPf45Q6jRA28qqSAA/edit?usp=sharing). Will eventually also be a file in the repo (e.g. decision-log.md).

**Comment by chadsansing** [comment]
Added the following to "Empower."

> Empowering contributors to be open leaders in their own right helps ensure the sustainability and maintenance of a project, creates opportunities for succession planning in open communities and projects, and helps make openness a renewable resource across communities of practice.

**Comment by chadsansing** [comment]
@stephwright, @zee-moz, @acabunoc - how do we feel about "Extensibility & sharing" as a header, or does "Extensibility" cover "Sharing."

Right now, "Participation & inclusion" is a special two-word heading at Mark's behest. If we also use "Extensibility & sharing," I feel like "Understanding" needs a +1. Then we need to explain why all 3 have 2 words and why we don't have 6 headings, etc.

I am content to let "Extensibility" hold sharing and for future curriculum, programming, and events to explain more explicitly.

Thoughts?

**Comment by chadsansing** [comment]
Looks like we have [before-and-after personas in the repo](https://github.com/mozilla/olm-whitepaper/blob/master/personas.md).

**Comment by zee-moz** [comment]
@chadsansing I think it probably does cover sharing, but think the word extensibility is tricky-- it's very specific to software engineering. One argument for adding "sharing" is that's at least familiar to everyone, and helps make this heading a bit more comprehensible to non-engineers. But I don't know that this outweighs the structural issues with word counts.

**Comment by chadsansing** [comment]
I hear you, @zee-moz; this reminds me of using GH, in general, and the tension between #mimi and passing along the tools/language that inform and capture the work and ideas. Good thing we have a beta to think about it more :)

**Comment by zee-moz** [comment]
@chadsansing what is #mimi again? i've heard it before but i don't hear it enough to remember...

**Comment by chadsansing** [comment]
"make it more inviting"

**Comment by chadsansing** [comment]
Added the following to "What is open leadership?"

> ***We think of Open Leadership as a set of principles, practices, and skills people can use to mobilize their communities to solve shared problems and achieve shared goals.*** The leadership part comes from mobilizing communities to solve problems and achieve goals. What makes open leadership "open," however, is the way that it shares roles and responsibilities for decision-making, content-creations, and information-sharing across a project community. Open leaders develop the systems and workflows that make their projects successful with the input and participation of volunteer contributors and users who draw value from being able to freely access, adapt, and change those projects for their own needs and the needs of their communities.

**Comment by edrushka** [comment]
I agree with Zannah's comment above that the word _extensibility_ is tough. It feels highly academic, and exclusive to an audience of engineers and system designers. I had to look it up. It reminds me of how the word interoperability is a stumbling block in the manifesto that requires it's own definition in parentheses.  

This opens a broader conversation about who is the desired audience for the map, and who you're looking for initial feedback from. If it's academics and systems designers, the word makes sense. If you're looking for a broader audience, including people that speak English as a second language,  I suggest using the word _sharing_ alone if it will suffice, or at least paired with _extensibility_.

**Comment by Saallen** [comment]
Plus 1 to @edrushka and @zee-moz. When I saw the work extensibility in the etherpad and even with the software context there- I still felt it was confusing and exclusive. If we keep share, people understand without explanation and it captures so much more

**Comment by stevanlohja** [comment]
"Feeling" it as confusing and exclusive is a subjective declaration with no context as to why. To exclude is the use of force while to not know is just be unknowing while anyone can take it upon themselves to know. It also requires the assumption that the broader society is non-English speaking and that the broader society won't understand "extensibility" which is the ironic prejudice of Marxist-like inter-sectional ideologue ✊✊✊✊

**Comment by chadsansing** [comment]
Without unduly limiting the scope of the discussion here, I'd encourage asking questions, like, "Can you explain that feeling more?", or, "Have we tested whether or not we can teach 'extensibility?'", or, "Does our community of intended users understand the term?", instead of unnecessarily aggressive forms of debate. 

I do think the ideology of the foundation is out of scope for this thread and should not be attributed to or borne by any individual's comments here.

I am happy to test "Sharing," but would also encourage continued discussion to find something between "sharing" and "extensibility" that can hold ideas of sustaining, maintaining, and adapting or remixing.

**Comment by stevanlohja** [comment]
Who is an example of the broader society and who is not part of the broader society? Would having a broader society class be divisive?

**Comment by chadsansing** [comment]
More importantly, for this thread, let's make a note to find opportunities to test share and extensibility during the beta and beyond.

I'm certain that broader society here means a general audience made up of people interested in - or merely curious about - openness and/or leadership from non-technical backgrounds and that the terms comes from a place of care, not division. 

Again, deciding who or who is not in broader society (writ large) is out of scope, and where we can reasonably infer what terms mean here, we should look for ways forward together rather than go out of scope. Your interest and past feedback have been appreciated, @stevanlohja; I'd invite suggestions about how to test language rather than out-of-scope arguments here.

From the [participation guidelines](https://github.com/mozilla/olm-whitepaper/blob/master/CODE_OF_CONDUCT.md):

- "[We agree to...] bring our best selves to the work and ***assume best intentions from others.***"
- "[We agree to...] ***work intentionally to make this project a safe and inviting space for all*** contributors and for contributors from all backgrounds.
- "[We also commit to...] follow the 50/50 rule: ***for each issue a person raises or for each problem a person identifies, they try to propose a solution***, as well.
- "[We also commit to...] follow the Nth rule: ***we will try to “speak” or comment only 1/Nth of the time*** to allow others to speak, where N is the total number of active contributors on the project.
- "[We also commit to...] ***avoid using jargon and ask for clarification when we need it.***"

**Comment by chadsansing** [comment]
Barring any feedback and discussion ahead of 2/2/18, I'll close this issue then ahead of the February OLM white paper beta.

**Comment by chadsansing** [comment]
[Join the beta!](https://medium.com/@chadsansing/join-the-open-leadership-map-beta-582446fb399d)
