### ISSUE TITLE
Should we make the white paper TOC appar in the sidebar?

### ISSUE THREAD

**Issue by chadsansing** [mozilla/olm-whitepaper#2]
Right now, the sidebar only has "White Paper." Would it improve navigation to include the paper's TOC in the sidebar for the white paper, as well? What do you think, @acabunoc?

**Comment by acabunoc** [comment]
+1 I'll work on formatting today! Ran out of time before the break. 

PSA: Did you know that if you upgrade to High Sierra it messes up your whole dev environment :(

**Comment by chadsansing** [comment]
Thanks, @acabunoc! I have refused the upgrade so far....

**Comment by acabunoc** [comment]
done! closing issue
