### ISSUE TITLE
We should discuss whether this white paper leads to a map or something else.

### ISSUE THREAD

**Issue by chadsansing** [mozilla/olm-whitepaper#24]
Are we building towards a dynamic map on the web? A framework? A set of standards?

**Comment by chadsansing** [comment]
Some initial thoughts:

- We could build a map. We would need to link out to curriculum/resources that we make or point to on partner sites.
- We could link to existing, revised resources like Open Leadership Training Series and Open Leadership 101.
- We could link to community public guidelines and Global Sprint or MozFest training webinars.
- We could link to mix and match activities from Working Open Workshops.
- We could be the "Open Leadership Framework" to inform our language across resources, events, and programming.
- We could be a framework for project analysis and personal and professional growth. Stronger with curriculum. Diagnostic tool/platform for open source.
- We could link this map or framework to a participation index as a means to structure, scaffold, and sequence funnel opportunities, e.g., as an open leader are you thinking systematically about user and contributor pathways, as well as content workflows?

I'm sure the answer is a "yes AND...," though perhaps we could star working toward, "Yes AND what?", here.

**Comment by stephwright** [comment]
I agree that "Open Leadership Framework" is the best title for this at this stage.  If we can make it happen, I'd ❤️ to see a map come out of this, primarily because we keep talking about open leadership programs in terms of a pathway... it's be great to have a map of that path.  Perhaps the map could be a separate thing in the future that combines this white paper with our "Mountain of Engagement"?

**Comment by chadsansing** [comment]
Great call, @stephwright. I'll close this issue and note that we will

- Change the name of this project to Open Map Leadership Framework when we release the gold version in March.
- Continue to work on the information architecture, design, and production tasks needed to make a true map later.
