### ISSUE TITLE
Best order for Open Principles (or should there be a set order)?

### ISSUE THREAD

**Issue by zee-moz** [mozilla/olm-whitepaper#25]
I'm preferring:

Understanding, Participation, Sharing --- it's a more satisfying narrative. You make something clear/accessible, people participate, and then remixing and sharing and building happens on that product.  Of course, it's not linear progression (you can return to any principle at any time, and share whenever) but it seems more logical to extend something that's already built with community help. 

Thoughts?

**Comment by chadsansing** [comment]
Agree that we should be flexible and am happy to go with consensus on ordering in our docs. I do like having participation & inclusion (P&I) last because of the rhetorical importance placed on the last item in a list. 

There are some cases where P&I come from getting the understanding and sharing pieces right, so to speak, and the are other cases where widespread sharing only happens after strong P&I efforts.

**Comment by chadsansing** [comment]
@zee-moz, pursuant to our conversation about change over time, I've added this to the section called "Who and what is this white paper for?"

> ....Moreover, the map itself will likely evolve over time as we discover more use cases for it in our work and in our wider community's work to share open practices. While it is in some ways limiting to start with any particular set of principles and practices, we believe it's important to share what we know and make this contribution to ongoing conversations about working open and open leadership in the world.
> 
> If you're curious about the kinds of use cases we evision and plan for the map, you can review and test these prototypes: 
> 
> - [Self assessment](https://docs.google.com/forms/d/e/1FAIpQLSds8B2aj6K0h7EwdKDBdqpIkGxReyOgrA4QRhrLim-Ags4rUw/viewform?usp=sf_link)
> - [Project design assessment](https://docs.google.com/forms/d/e/1FAIpQLSesg4Uk7Znn5VawGQd99eTIlAsNyPXv9TdLeJhfYj2mxtlv4w/viewform?usp=sf_link)
> - [Project postmortem](https://docs.google.com/forms/d/e/1FAIpQLScckWbuQuXut4y_Brp3yTr9dqPVPPwdlaxMyM_8cFLgACSFaA/viewform?usp=sf_link)
> - [Applications survey](https://docs.google.com/forms/d/e/1FAIpQLSdPKwWh_3euSwKyjAmJVSKsR_gjBkMsq-SJ48lLGrGicEQo3g/viewform?usp=sf_link)

**Comment by stephwright** [comment]
I concur with having P&I listed last in the white paper list for the reasons you explained, @chadsansing around things in the middle of the list getting lost.  Though also think there may be times that it may make more sense for the order @zee-moz suggested.  I'm not sure we need to always have it in the same order through all our materials (thinking for example of Internet Health issues... I don't think they're listed in the same order in all our documentation of them), though I do like the consistency of having them in the same order throughout the white paper.

**Comment by chadsansing** [comment]
Thanks, @stephwright -

How does that sound to you, @zee-moz? We'll leave the white paper order as is, but adapt the order in other resources as needed. Sound right?

**Comment by zee-moz** [comment]
fine with me.

**Comment by chadsansing** [comment]
Closing.
