### ISSUE TITLE
Fix formatting on the README

### ISSUE THREAD

**Issue by chadsansing** [mozilla/olm-whitepaper#3]
@acabunoc, I wrecked the formatting about halfway down, but I'm not sure how. Suggestions for fixing it?

**Comment by chadsansing** [comment]
Line 35.

**Comment by acabunoc** [comment]
taking a look now!

**Comment by acabunoc** [comment]
There was an unattended merge conflict in the file!

(my editor also removed trailing whitespaces)
https://github.com/mozilla/olm-whitepaper/commit/56299858eea14273f5b016f8abba03edf731aa8a

Read more:
https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/

**Comment by chadsansing** [comment]
Ah, I see - I will try it out next time there's a merge conflict :) Thanks, @acabunoc!

**Comment by acabunoc** [comment]
This might be a better article to go through if it comes up again! https://help.github.com/articles/about-merge-conflicts/

I hear you can also fix them in the github ui now -- I haven't tried it but it sounds fancy
