### ISSUE TITLE
We should increase the number and accessibility of ways to give feedback.

### ISSUE THREAD

**Issue by chadsansing** [mozilla/olm-whitepaper#9]
From the [blog](https://medium.com/@dajbelshaw/great-stuff-chad-and-im-delighted-about-this-work-4f6b91cb541c):

> Great stuff, Chad — and I’m delighted about this work. I’d like this to be even more open than feedback via email or GitHub, though. How could you push those boundaries?

**Comment by chadsansing** [comment]
Suggestions include community calls and a wiki thus far.

**Comment by chadsansing** [comment]
[Community calls](https://public.etherpad-mozilla.org/p/olm-whitepaper-call) scheduled.

**Comment by chadsansing** [comment]
@Saallen, @edrushka, @zee-moz, @acabunoc - anything near-term we could do here in addition to the community calls? Ideas for a beta? Would we use a GoogleDoc or wiki for the beta? Other pathways for contribution?

**Comment by Saallen** [comment]
How about Discourse, google doc with suggestions turned on or open office calls designed around specific areas?

**Comment by edrushka** [comment]
It might be worth studying the re-branding exercise that Mozilla conducted in 2016. That team generated enormous discussion via comments on their blogs. Granted, people love weighing in on visual design and the logo was something people felt strongly about, but I think the branding team also deserves credit for fostering conversation by blogging regularly about the process along the way.  https://blog.mozilla.org/opendesign/

**Comment by chadsansing** [comment]
@edrushka, that would be cool; I feel like we'd need a bigger idea of where we're going with the map (as a team, as an org) to contextualize where we are. Another agenda item, perhaps, for a team meeting soon.

**Comment by chadsansing** [comment]
For the  February beta and beyond:

- GDoc
- Office hours
- Community call
- Weeknote blog posts

After that, we can evaluate where the white paper launch should live to encourage on-going feedback and improvement.

Closing for now; will open an issue on the beta re: where to put the launch version.
